### ISSUE TITLE
problem on coreelec

### ISSUE THREAD

**Issue by ananias47** [osumoclement/script.black.bars.never#1]
hi my friend i find out that on windows 10 works well but on coreelec in some cases doesnt work

**Comment by osumoclement** [comment]
Hi, I am investigating this. It doesn't seem to work on many of these kinds of due to something to how they render video. Can you disable hardware acceleration and try see if it now works?

**Comment by ananias47** [comment]
yes my friend with hardware acceleration off it works well but the odd thing is that manual zoom works well on coreelec in videos where your addon dont work. 
ps : i know that on android version of kodi doesnt work manual zoom either

**Comment by osumoclement** [comment]
So with hardware acceleration turned off the addon works well in all videos?

**Comment by ananias47** [comment]
yes but the videos are laggy

**Comment by osumoclement** [comment]
I have same problem so this needs investigation. It may take a while to solve though

**Comment by osumoclement** [comment]
Hi, there's a new release which _sort of_ helps in cases like these. Try it out (enable the Android workaround) and let me know if it helps

**Comment by ananias47** [comment]
I try it on coreelec and it give me many log errors and it doesn't work

**Comment by osumoclement** [comment]
Can you post a screenshot of the errors I check

**Comment by ananias47** [comment]
![Screenshot_20230620_165337_ES File Explorer](https://github.com/osumoclement/script.black.bars.never/assets/6560173/824890d5-7c74-411d-aac6-d1c597994978)
![Screenshot_20230620_165343_ES File Explorer](https://github.com/osumoclement/script.black.bars.never/assets/6560173/38bf2070-5340-4448-b1e4-f6b01a96b966)
![Screenshot_20230620_165349_ES File Explorer](https://github.com/osumoclement/script.black.bars.never/assets/6560173/f4dc2b9b-6dfe-439f-b60d-b5c6f29f9d42)
![Screenshot_20230620_165359_ES File Explorer](https://github.com/osumoclement/script.black.bars.never/assets/6560173/5da6c9f6-b3f3-40c0-a476-8919aa144567)

**Comment by osumoclement** [comment]
I have uploaded new code, use it and tell me if it works

**Comment by ananias47** [comment]
I try it but nothing happened and i have this errors when i press toggle status 
![Screenshot_20230620_175828_ES File Explorer](https://github.com/osumoclement/script.black.bars.never/assets/6560173/9042fd8f-fab9-43f3-b549-40325ca70208)
![Screenshot_20230620_175821_ES File Explorer](https://github.com/osumoclement/script.black.bars.never/assets/6560173/8fa2dc71-320c-4773-ab11-6e5697eb2a78)

**Comment by osumoclement** [comment]
Okay, send screenshot of addon settings

**Comment by ananias47** [comment]
What i must sent?? I already did it on previous post

**Comment by TwilightMercy** [comment]
You need to configure the addon settings exactly like in the picture, no need to press Toggle status 

![image](https://github.com/osumoclement/script.black.bars.never/assets/29895680/c99c05d4-6a16-493d-9111-859e6af3b51e)

**Comment by ananias47** [comment]
I already did this

**Comment by ananias47** [comment]
Hi i tested it on android and it seems that it doesn't work

**Comment by osumoclement** [comment]
I have identified the problem will fix soon

**Comment by osumoclement** [comment]
There's a new release which should work

**Comment by ananias47** [comment]
hi my friend now i tested it and it works on movies but it doesnt work on same episodes on series and on netflix addon

**Comment by osumoclement** [comment]
Okay, will investigate

**Comment by Benik3** [comment]
Hi. You wrote in readme that capturing doesn't work on Coreelec with HW acceleration.
But Hyperion add-on (which grab screen and drive ambilight LEDs) works fine. Maybe it could help you with grabbing screen on Coreelec :)

**Comment by osumoclement** [comment]
Hi. You have CoreELEC? And Hyperion works with hardware acceleration enabled?

**Comment by Benik3** [comment]
Yeap I have Coreelec 20 on x96 box (amlogic s905x3).  
The hyperion works without any problem with HW acceleration enabled.

**Comment by osumoclement** [comment]
I see, have you tried this addon on the CoreELEC? Does it work?

**Comment by Benik3** [comment]
I'm now out of my home, but I can test it next week :)

**Comment by osumoclement** [comment]
Okay :)

**Comment by TwilightMercy** [comment]
@Benik3 Update when you’ll can Android support is important:)

**Comment by Benik3** [comment]
@TwilightMercy I have Coreelec (Linux), not Android.

Anyway I tried it and it doesn't work on Coreelec. In log I have:
```
2023-07-16 20:59:11.288 T:9667    error <general>: CRenderManager::Capture - unknown capture id: 0
2023-07-16 20:59:11.288 T:9667     info <general>: Interim Aspect Ratio = 178
2023-07-16 20:59:11.291 T:9667    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: bytearray index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.black.bars.never/addon.py", line 34, in onAVStarted
                                                       self.abolishBlackBars()
                                                     File "/storage/.kodi/addons/script.black.bars.never/addon.py", line 132, in abolishBlackBars
                                                       aspectratio = self.GetAspectRatioFromFrame()
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.black.bars.never/addon.py", line 89, in GetAspectRatioFromFrame
                                                       __middleScreenDark = self.LineColorLessThan(
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.black.bars.never/addon.py", line 60, in LineColorLessThan
                                                       _bArray[i] &= 0x00
                                                       ~~~~~~~^^^
                                                   IndexError: bytearray index out of range
                                                   -->End of Python script error report<--
```

**Comment by osumoclement** [comment]
It's strange because I checked Hyperion and the code they use is same as what I'm using to grab screenshot. I'll do more investigation

**Comment by Benik3** [comment]
I think that Hyperion doesn't use CRenderManager, but special Amlogic grabber...
https://github.com/hyperion-project/hyperion.ng/blob/64642a44578fe48dce8144c23180d29c160c7906/libsrc/grabber/amlogic/AmlogicGrabber.cpp

**Comment by osumoclement** [comment]
I think Hyperion uses a standalone app different from Kodi to achieve the screenshot. Wouldn't work for this addon because of that, but means Kodi could use their strategy to implement this in Kodi app internally

**Comment by TwilightMercy** [comment]
Is there any open issue about that in Kodi’s github?

**Comment by osumoclement** [comment]
I don't think so

**Comment by Benik3** [comment]
> I think Hyperion uses a standalone app different from Kodi to achieve the screenshot. Wouldn't work for this addon because of that, but means Kodi could use their strategy to implement this in Kodi app internally

You are right. Hyperion runs as standalone app, there is just add-on for the app so the Hyperion can be controlled from Kodi (e.g. by play/pause of video).

**Comment by osumoclement** [comment]
Yes, and they do the screenshot using some workarounds specific to CoreELEC, so maybe Kodi could copy that
