### ISSUE TITLE
[Question] Opening “Zoom amount” window through python code

### ISSUE THREAD

**Issue by TwilightMercy** [osumoclement/script.black.bars.never#4]
Hi friend,

In the meantime, until the android workaround is in development to perfection, I want to configure in Estuary’s player OSD a button to simply open the manual zoom slider available in Video settings in player - “Zoom amount”:
![image](https://github.com/osumoclement/script.black.bars.never/assets/29895680/9b1d12cd-2ce0-4903-9469-faefb21d098f)

![image](https://github.com/osumoclement/script.black.bars.never/assets/29895680/b86b5d36-21df-43dc-bc92-b7a50c4a2c86)

For simple “onclick” function in skin’s VideoOSD.xml file, I only found that it’s possible to do ZoomIn/ZoomOut functions:
![image](https://github.com/osumoclement/script.black.bars.never/assets/29895680/0999951f-1a6f-489c-a664-52c52bb11c90)

But I’m looking for a direct shortcut to “Zoom Amount” window, for manually moving the slider. 
Do you know if it’s possible with small python code as a small Kodi addon?

Thanks.

**Comment by osumoclement** [comment]
From looking at logs in KODI, the window activated is sliderdialog [ID 1045](https://kodi.wiki/view/Window_IDs#Window_IDs). So I also think it works similarly to how you implemented the addon toggle, meaning you have to read current values and increment manually. [Reference for slider](https://alwinesch.github.io/group__python__xbmcgui__control__slider.html). So logic is this:

1. Instantiate slider, read current zoom amount and use `setPercent` to set the initial position
2. React to left and right buttons to move slider appropriately and at the same time setting the actual zoom

**Comment by TwilightMercy** [comment]
Wouldn’t be opening the window 10145 “sliderdialog” be enough?
To open this:
![image](https://github.com/osumoclement/script.black.bars.never/assets/29895680/8a4f1305-5156-4b3d-aa42-8830b3777b4b)


And it will work as usual like opening it in manually in Kodi?

**Comment by osumoclement** [comment]
I don't think so. The dialog is reusable, which means it doesn't exist specifically for just zooming. Here's the code where it gets created [as seen here](https://github.com/xbmc/xbmc/blob/master/xbmc/video/dialogs/GUIDialogVideoSettings.cpp):

```
if (g_application.GetAppPlayer().Supports(RENDERFEATURE_ZOOM))
    AddSlider(groupVideo, SETTING_VIDEO_ZOOM, 216, SettingLevel::Basic,
              videoSettings.m_CustomZoomAmount, "{:2.2f}", 0.5f, 0.01f, 2.0f, 216, usePopup);
```

**Comment by TwilightMercy** [comment]
I see, thanks for the explanation, I’m not that experienced in that area. 

Is it hard/complicated to make a small python code addon to reproduce the “Zoom amount” window on button press? I’m afraid I don’t have the knowledge for that.

**Comment by osumoclement** [comment]
Not too difficult. I'll give it a try sometime next week

**Comment by TwilightMercy** [comment]
Thank you, appreciated.

**Comment by osumoclement** [comment]
Hey. Do you know an addon which uses Control Slider?

**Comment by TwilightMercy** [comment]
I don't think I know something for OSD. I found this in Kodi forum if it helps:

https://forum.kodi.tv/showthread.php?tid=372010

**Comment by TwilightMercy** [comment]
> Hey. Do you know an addon which uses Control Slider?

I know that FEN addon has control slider but in addon settings
![image](https://github.com/osumoclement/script.black.bars.never/assets/29895680/e9efe8ee-3adb-4154-bb86-f59777773293)

**Comment by osumoclement** [comment]
I give up, I have gotten only as far as showing a Control Slider which for some reason looks weird, like a webpage without CSS. Would have uploaded screenshot but don't know how

**Comment by TwilightMercy** [comment]
Just press "Prt screen" button in keyboard and paste directly here

Anyway, don't give up : ) If you can make it work (regardless the design), I have a friend who knows to design addon/skins and stuff.

**Comment by osumoclement** [comment]
![image](https://github.com/osumoclement/script.black.bars.never/assets/19283490/e283d451-1fad-4c24-9612-45bda33b0934)

**Comment by TwilightMercy** [comment]
Haha :) but don’t worry about it, I’ll later give it to my friend to check
The goal if possible to open this slider in player OSD with button that have “onclick” function similar to black bars never, like:
RunScript(addon_name, function)

**Comment by osumoclement** [comment]
Yes. If you look at [this](https://forum.kodi.tv/showthread.php?tid=372010) he is using XML like you did (while I am using Python). From [here](https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/570b8959060b2e6a439b71fa31b211d617cd7086/1080i/Includes_OSD.xml#L645-L837) you can see the code will look like this

```
<include name="OSD_PlaySpeed_Label">
        <param name="width">52</param>
        <param name="selected">false</param>
        <param name="textcolor">dialog_fg_70</param>
        <definition>
            <control type="label">
                <font>font_tiny</font>
                <label>$PARAM[label]</label>
                <include content="Object_TextColor" condition="$PARAM[selected]">
                    <param name="textcolor">$VAR[ColorSelected]</param>
                </include>
                <textcolor>$PARAM[textcolor]</textcolor>
                <width>$PARAM[width]</width>
                <align>center</align>
            </control>
        </definition>
    </include>
```

**Comment by osumoclement** [comment]
So this is what I have right now, if they could modify it to use XML for ControlSlider instead (or make it look good in Python) then it would be okay [script.zoomshortcut (1).zip](https://github.com/osumoclement/script.black.bars.never/files/11926027/script.zoomshortcut.1.zip)

**Comment by TwilightMercy** [comment]
I've installed it and it opened the scroller with the big white circle
How can I call in the the player to activate it? and will using right/left keys in keyboard will move the zoom slider?

**Comment by osumoclement** [comment]
> Then increment/deincrement values using \<onleft\> and \<onright\> with conditionals.

From the link I gave seems you're supposed to react to left and right manually for example like this
`<onleft>incrementZoom()</onleft>`

**Comment by TwilightMercy** [comment]
I see, I thought (if possible) that the python code itself will open the slider and react to left/right which will change the zoom

Or it isn’t?

**Comment by osumoclement** [comment]
Seems for most things Kodi offers both Python way and XML way. But documentation too lacking
