### ISSUE TITLE
Add ability to set keymap

### ISSUE THREAD

**Issue by louisefindlay23** [osumoclement/script.black.bars.never#5]
It would be great to have an option in the addon settings to set a keymap for the toggle script similar to the [VPN Manager](https://github.com/Zomboided/service.vpn.manager) addon.

**Comment by osumoclement** [comment]
Sounds good, added to list of features to do

**Comment by TwilightMercy** [comment]
Will it affect the existing “toggle” function? I’m using it as a button in my skin

**Comment by osumoclement** [comment]
It shouldn't affect that at all

**Comment by osumoclement** [comment]
Closing this as toggle keymap ability has been added to the addon
