### ISSUE TITLE
Doesn't work on Kodi v20.3 for Android TV

### ISSUE THREAD

**Issue by robmausser** [osumoclement/script.black.bars.never#6]
On Kodi v20.3 for Android TV (Google TV on Chromecast) the add-on doesnt work. Toggling on gives error message.

**Comment by osumoclement** [comment]
Did you enable the Android & Embedded Systems Workaround from the addon settings?

**Comment by robmausser** [comment]
Yes I did. Same issue

**Comment by robmausser** [comment]
Nevermind its working. It throws an error when you toggle in app settings
but it still works. I thought the app removed black bars that were also
burned into the video, but that appears its not the case.

**Comment by osumoclement** [comment]
What error do you get when you toggle?

> I thought the app removed black bars that were also
burned into the video

It does, is your Android TV connected to internet? What film/episode is it not working for? Does it give any notification?

**Comment by robmausser** [comment]
It doesn't for streaming stuff like this

https://www.matthuisman.nz/2020/10/pluto-tv-kodi-add-on.html

It probably can't get metadata properly for something like this and would
need a screenshot, which I understand isn't possible on Android.

No worries

**Comment by osumoclement** [comment]
Ah, yes. That's a technical limitation. I do need to include that on the addon description.
> It probably can't get metadata

Yup
